"""
dashboard/detail_helpers.py — 단일 개체 분석(05) 보조 함수
─────────────────────────────────────────────────────────────
Streamlit 비의존 순수 함수만 모은다(테스트 용이·페이지 슬림화 목적).
  · compute_embedding : 개체 평균 점수 → 2D 임베딩(UMAP, 없으면 PCA)
  · path_length       : 좌표 시퀀스 → 총 이동 경로 길이(px)
  · build_report_pdf  : 개체 리포트를 PDF(bytes)로 생성
  · build_comparison_pdf  : 비교 분석 결과를 PDF로 생성 (표준 리포트 / 논문 스타일)
  · build_comparison_pptx : 비교 분석 결과를 PPTX로 생성 (프레젠테이션 스타일)
"""
import io
import textwrap
from datetime import datetime

import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

from src.constants import SCORE_COLS, BEH_KR


def draw_wrapped_text(fig, x, y, text, fontsize, color, width=80, line_height=0.015):
    """지정한 글자수(width) 단위로 줄바꿈을 처리하여 PDF에 출력하고, 다음 y 시작점을 반환한다.
    공백이나 줄바꿈이 많은 텍스트가 겹치지 않게 방지하는 헬퍼 함수."""
    current_y = y
    paragraphs = text.split('\n')
    for para in paragraphs:
        wrapped_lines = textwrap.wrap(para, width=width)
        if not wrapped_lines:
            # 빈 줄 처리
            current_y -= line_height
            continue
        for line in wrapped_lines:
            fig.text(x, current_y, line, fontsize=fontsize, color=color, va='top')
            current_y -= line_height
    return current_y


def compute_embedding(df_m):
    """개체별 평균 점수(df_m[SCORE_COLS]) → 2D 좌표(D1,D2) 추가.
    UMAP 설치 시 UMAP, 아니면 PCA 로 폴백. (out_df, 사용기법) 반환."""
    X = df_m[SCORE_COLS].values
    try:
        from umap import UMAP as _UMAP
        coords = _UMAP(n_components=2, n_neighbors=8, random_state=42).fit_transform(X)
        method = "UMAP"
    except Exception:
        coords = PCA(n_components=2).fit_transform(X)
        method = "PCA"
    out = df_m.copy()
    out['D1'], out['D2'] = coords[:, 0], coords[:, 1]
    return out, method


def path_length(df_xy):
    """연속 좌표(x,y) 간 유클리드 거리 합 = 총 이동 경로 길이(px)."""
    if df_xy.empty:
        return 0.0
    d = np.sqrt(df_xy['x'].diff() ** 2 + df_xy['y'].diff() ** 2)
    return float(d.sum())


def build_report_pdf(animal, dose, means, ctrl, ai_text, coords):
    """개체 행동 분석 리포트를 PDF(bytes)로 생성한다 (matplotlib PdfPages).
    입력: means(개체 평균 점수), ctrl(대조군 평균), ai_text(요약), coords(궤적 좌표)."""
    from matplotlib.backends.backend_pdf import PdfPages
    buf = io.BytesIO()
    with PdfPages(buf) as pdf:
        fig = plt.figure(figsize=(8.27, 11.69))  # A4
        fig.subplots_adjust(left=0.08, right=0.95, top=0.94, bottom=0.06, hspace=0.55)

        # 헤더
        fig.text(0.08, 0.96, f"마우스 {animal} 행동 분석 리포트", fontsize=18, fontweight='bold', color='#0f172a')
        fig.text(0.08, 0.935, f"소속 그룹: Yohimbine {dose} mg/kg 투여군    "
                              f"생성일: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
                 fontsize=9, color='#64748b')
        fig.add_artist(plt.Line2D([0.08, 0.92], [0.925, 0.925], color='#e2e8f0', lw=1, transform=fig.transFigure))

        # 1. AI 요약
        fig.text(0.08, 0.90, "1. AI 분석 요약", fontsize=12, fontweight='bold', color='#1e293b')
        fig.text(0.08, 0.84, ai_text, fontsize=10, color='#334155', wrap=True, va='top')

        # 2. 행동 지표 막대 (개체 vs 대조군)
        ax1 = fig.add_axes([0.08, 0.50, 0.84, 0.22])
        labels = [BEH_KR[c] for c in SCORE_COLS]
        mvals = [means[c] * 100 for c in SCORE_COLS]
        cvals = [ctrl[c] * 100 if ctrl is not None else 0 for c in SCORE_COLS]
        x = np.arange(len(labels)); w = 0.38
        ax1.bar(x - w / 2, cvals, w, label='대조군(Dose 0)', color='#4C72B0')
        ax1.bar(x + w / 2, mvals, w, label='현재 개체', color='#C44E52')
        ax1.set_xticks(x); ax1.set_xticklabels(labels, fontsize=9)
        ax1.set_ylabel('평균 점수 (0~100)', fontsize=9)
        ax1.set_title('2. 행동 지표 비교 (개체 vs 대조군)', fontsize=12, fontweight='bold', loc='left', color='#1e293b')
        ax1.legend(fontsize=8, frameon=False)
        for sp in ['top', 'right']:
            ax1.spines[sp].set_visible(False)

        # 3. 궤적 / 4. 히트맵
        if coords is not None and not coords.empty:
            ax2 = fig.add_axes([0.08, 0.10, 0.40, 0.30])
            ax2.scatter(coords['x'], coords['y'], c=coords['frame'], cmap='viridis', s=2, alpha=0.6)
            ax2.set_aspect('equal'); ax2.invert_yaxis(); ax2.set_xticks([]); ax2.set_yticks([])
            ax2.set_title('3. 이동 궤적', fontsize=11, fontweight='bold', loc='left', color='#1e293b')

            ax3 = fig.add_axes([0.54, 0.10, 0.38, 0.30])
            ax3.hist2d(coords['x'], coords['y'], bins=40, cmap='YlOrRd')
            ax3.set_aspect('equal'); ax3.invert_yaxis(); ax3.set_xticks([]); ax3.set_yticks([])
            ax3.set_title('4. 공간 히트맵', fontsize=11, fontweight='bold', loc='left', color='#1e293b')

        fig.text(0.08, 0.03, "Generated by Laboratory AI Platform", fontsize=8, color='#94a3b8')
        pdf.savefig(fig)
        plt.close(fig)
    buf.seek(0)
    return buf.getvalue()


def build_comparison_pdf(cfg, result, disp, lines, comp_type="group"):
    """비교 분석 결과를 PDF로 생성 (표준 리포트 / 논문 스타일)"""
    from matplotlib.backends.backend_pdf import PdfPages
    import matplotlib.pyplot as plt
    import numpy as np
    import pandas as pd
    import io
    from datetime import datetime

    plt.rcParams['font.family'] = 'Malgun Gothic'
    plt.rcParams['axes.unicode_minus'] = False

    buf = io.BytesIO()
    with PdfPages(buf) as pdf:
        fig = plt.figure(figsize=(8.27, 11.69))  # A4
        
        title_text = cfg.get("title", "비교 분석 리포트")
        template = cfg.get("template", "표준 리포트")
        base_d = cfg.get("base_dose", 0)
        comp_ds = cfg.get("comp_doses", [6])

        if template == "논문 스타일":
            # ────────────────── 논문 스타일 (Academic Style) ──────────────────
            fig.subplots_adjust(left=0.08, right=0.92, top=0.92, bottom=0.08)
            
            fig.text(0.08, 0.95, "Journal of Behavioral Neuroscience | Research Article", fontsize=8.5, style='italic', color='#475569')
            fig.add_artist(plt.Line2D([0.08, 0.92], [0.94, 0.94], color='#1e293b', lw=1.5, transform=fig.transFigure))
            
            fig.text(0.08, 0.90, title_text, fontsize=16, fontweight='bold', color='#0f172a')
            fig.text(0.08, 0.87, "Laboratory AI Platform Research Team", fontsize=9, color='#334155', fontweight='semibold')
            fig.text(0.08, 0.855, "Department of Pharmacology & Behavior, Bio-Neuroscience Institute", fontsize=8, color='#64748b')
            
            fig.add_artist(plt.Line2D([0.08, 0.92], [0.84, 0.84], color='#cbd5e1', lw=0.5, transform=fig.transFigure))
            
            y_pos = 0.82
            
            # I. 서론
            fig.text(0.08, y_pos, "I. 서론 및 연구 목적 (Introduction)", fontsize=11, fontweight='bold', color='#1e293b')
            y_pos -= 0.02
            if comp_type == "group":
                intro_text = (
                    f"본 연구는 요힘빈(Yohimbine) 약물 투여 조건 하에서 마우스의 행동적 특성(Behavioral Phenotypes) 변화를 정량적으로 탐색하고자 수행되었습니다. "
                    f"대조군(Dose {base_d} mg/kg, n={result['meta']['n_base']}) 대비 실험군(Dose {', '.join(str(d) for d in comp_ds)} mg/kg, n={result['meta']['n_comp']})의 "
                    f"5대 핵심 행동 도메인(이동성, 탐색성, 불안, 과활동성, 경직)을 분석하여 약물이 뇌와 행동 모델에 미치는 영향을 검증하였습니다."
                )
            elif comp_type == "individual":
                intro_text = (
                    f"본 연구는 동일한 실험 조건 내에 포함된 서로 다른 두 마우스 개체(개체 A: {cfg['a_animal']} vs 개체 B: {cfg['b_animal']}) 간의 "
                    f"행동적 특징 차이를 개체 수준에서 세밀하게 탐색하고 정량적으로 대조 분석하고자 설계되었습니다."
                )
            else: # time
                intro_text = (
                    f"본 연구는 요힘빈 투여 마우스 개체({cfg['animal']})의 실험 시간 경과에 따른 행동 스코어 추이를 "
                    f"총 {cfg['n_win']}개 구간으로 세분화하여 종단적인 행동 강도 변화 양상을 조사하기 위해 수행되었습니다."
                )
            y_pos = draw_wrapped_text(fig, 0.08, y_pos, intro_text, 8.5, '#334155', width=90, line_height=0.015)
            y_pos -= 0.02

            # II. 재료 및 방법
            fig.text(0.08, y_pos, "II. 실험 방법 및 통계 분석 (Materials & Methods)", fontsize=11, fontweight='bold', color='#1e293b')
            y_pos -= 0.02
            if comp_type == "group":
                method_text = (
                    "실험 동물의 행동은 오픈 필드(Open Field) 챔버에서 기록되었으며, DLC(DeepLabCut) 트래킹 벡터 및 동물 행동학적 규칙 기반 가중치를 적용하여 "
                    "연속적인 행동 강도 점수를 획득했습니다. 통계적 신뢰성을 확보하기 위해 개체 간 선천적 편차를 임의 효과(Random Effect)로 통제한 "
                    "선형 혼합 효과 모델(Linear Mixed-Effects Model, LME)을 구성하여 고정 효과(Fixed Effect, 약물 투여) 검정을 실시했습니다."
                )
            elif comp_type == "individual":
                method_text = (
                    "동일 실험 챔버 내에서 기록된 각 개체의 5대 행동 지표 시퀀스를 바탕으로 평균 강도 수치를 도출했습니다. "
                    "두 개체 집단 간 평균 행동 스코어 편차의 통계적 유의성은 양측 독립표본 t-검정(Student's t-test)을 통해 확인했으며, "
                    "효과 크기를 가늠하기 위해 Cohen's d 지표를 계산했습니다."
                )
            else: # time
                method_text = (
                    "동일 개체의 전체 실험 기록 세션을 설정된 개수(Time Windows)대로 균등 분할하여 각 구간별 평균 행동 스코어를 산출했습니다. "
                    "행동 양상의 시간에 따른 전이 흐름을 분석하기 위해 첫 구간 대비 마지막 구간의 변화율과 시계열적 추이를 산정하고 "
                    "통계적 검정을 시행했습니다."
                )
            y_pos = draw_wrapped_text(fig, 0.08, y_pos, method_text, 8.5, '#334155', width=90, line_height=0.015)
            y_pos -= 0.02

            # III. 실험 결과
            fig.text(0.08, y_pos, "III. 통계적 분석 결과 (Results)", fontsize=11, fontweight='bold', color='#1e293b')
            y_pos -= 0.025
            
            fig.text(0.08, y_pos, "Table 1. Statistical Analysis and Behavioral Descriptive Summary", fontsize=8.5, style='italic', fontweight='semibold', color='#1e293b')
            
            # Table (높이를 0.13으로 소폭 줄임)
            ax_table = fig.add_axes([0.08, y_pos - 0.15, 0.84, 0.13])
            ax_table.axis('off')
            
            cell_text = []
            for _, row in disp.iterrows():
                line_cells = []
                for col in disp.columns:
                    val = str(row[col])
                    if col == "행동 지표":
                        val = val.split(' ')[0]
                    line_cells.append(val)
                cell_text.append(line_cells)
                
            # Translate headers
            translation = {
                "행동 지표": "Behavior", "대조군 평균": "Control Mean", "실험군 평균": "Exp Mean",
                "변화율(%)": "Change(%)", "차이(B-A)": "Diff (B-A)", "변화(첫→끝)": "Trend",
                "유의성": "Significance", "t-검정 p": "t-pval", "LME 계수": "LME Coef", "LME p": "LME p-val"
            }
            columns = [translation.get(col, col) for col in disp.columns]
            columns = [col.replace("개체 A", "Animal A").replace("개체 B", "Animal B") for col in columns]
            
            table = ax_table.table(cellText=cell_text, colLabels=columns, loc='center', cellLoc='center')
            table.auto_set_font_size(False)
            table.set_fontsize(8)
            table.scale(1.0, 1.15) # 스케일을 1.4에서 1.15로 낮춰 높이가 영역을 넘지 않도록 함
            
            # APA style
            for (r_idx, c_idx), cell in table.get_celld().items():
                cell.set_facecolor('#ffffff')
                cell.get_text().set_color('#1e293b')
                if r_idx == 0:
                    cell.visible_edges = 'TB'
                    cell.get_text().set_weight('bold')
                elif r_idx == len(disp):
                    cell.visible_edges = 'B'
                else:
                    cell.visible_edges = ''
                    
            y_pos -= 0.18 # 테이블 밑 여백 고려하여 강하

            # Figure 1 Chart (차트 높이를 0.08로 축소하고 범례를 그래프 밖으로 이동)
            ax_chart = fig.add_axes([0.08, y_pos - 0.12, 0.84, 0.08])
            x_indices = np.arange(len(disp))
            
            if comp_type == "group":
                w = 0.3
                ax_chart.bar(x_indices - w/2, disp["대조군 평균"], w, label=f"Control (Dose {base_d})", color='#4C72B0')
                ax_chart.bar(x_indices + w/2, disp["실험군 평균"], w, label="Exp Group", color='#C44E52')
                ax_chart.legend(fontsize=7, frameon=False, loc='lower left', bbox_to_anchor=(0.0, 1.02), ncol=2)
            elif comp_type == "individual":
                # 호출부에서 '개체 A/B 평균' 컬럼이 '대조군/실험군 평균'으로 rename 되어 넘어온다.
                a_col = "대조군 평균" if "대조군 평균" in disp.columns else [c for c in disp.columns if "개체 A" in c][0]
                b_col = "실험군 평균" if "실험군 평균" in disp.columns else [c for c in disp.columns if "개체 B" in c][0]
                w = 0.3
                ax_chart.bar(x_indices - w/2, disp[a_col], w, label="Animal A", color='#4C72B0')
                ax_chart.bar(x_indices + w/2, disp[b_col], w, label="Animal B", color='#C44E52')
                ax_chart.legend(fontsize=7, frameon=False, loc='lower left', bbox_to_anchor=(0.0, 1.02), ncol=2)
            else: # time
                win_cols = [c for c in disp.columns if "구간" in c]
                n_w = len(win_cols)
                w = 0.8 / n_w
                colors = ['#4C72B0', '#55A868', '#C44E52', '#8172B2', '#CCB974', '#64B5CD']
                for idx, win in enumerate(win_cols):
                    ax_chart.bar(x_indices - 0.4 + (idx + 0.5)*w, disp[win], w, label=win, color=colors[idx % len(colors)])
                ax_chart.legend(fontsize=7, frameon=False, loc='lower left', bbox_to_anchor=(0.0, 1.02), ncol=n_w)

            ax_chart.set_xticks(x_indices)
            ax_chart.set_xticklabels([name.split(' ')[0] for name in disp["행동 지표"]], fontsize=8)
            ax_chart.set_ylabel('Mean Score', fontsize=8)
            for sp in ['top', 'right']:
                ax_chart.spines[sp].set_visible(False)
            ax_chart.spines['bottom'].set_color('#cbd5e1')
            ax_chart.spines['left'].set_color('#cbd5e1')
            
            caption_y = y_pos - 0.165
            fig.text(0.08, caption_y, "Figure 1. Comparison of major behavioral intensity scores.", fontsize=8, style='italic', color='#475569')
            
            y_pos -= 0.20

            # IV. 고찰 및 결론
            fig.text(0.08, y_pos, "IV. 고찰 및 결론 (Discussion & Conclusion)", fontsize=11, fontweight='bold', color='#1e293b')
            y_pos -= 0.02
            
            ai_desc = ""
            if lines:
                ai_desc = "• " + "\n• ".join(lines)
            else:
                ai_desc = "• 통계분석 유의수준(p < 0.05) 하에서 관찰 대상 지표들의 변화율 혹은 격차는 정상 범위 내에 위치하여 유의미한 행동 수치 편향은 발견되지 않았습니다."
                
            y_pos = draw_wrapped_text(fig, 0.08, y_pos, ai_desc, 8, '#334155', width=95, line_height=0.014)
            
        else:
            # ────────────────── 표준 리포트 스타일 (Standard Style) ──────────────────
            fig.subplots_adjust(left=0.08, right=0.92, top=0.92, bottom=0.08)
            
            fig.text(0.08, 0.95, title_text, fontsize=18, fontweight='bold', color='#0f172a')
            if comp_type == "group":
                meta_text = (
                    f"생성일: {datetime.now().strftime('%Y-%m-%d %H:%M')}    "
                    f"대조군: Dose {base_d} ({result['meta']['n_base']}마리)    "
                    f"실험군: Dose {', '.join(str(d) for d in comp_ds)} ({result['meta']['n_comp']}마리)"
                )
            elif comp_type == "individual":
                meta_text = (
                    f"생성일: {datetime.now().strftime('%Y-%m-%d %H:%M')}    "
                    f"개체 A: {cfg['a_animal']}    "
                    f"개체 B: {cfg['b_animal']}"
                )
            else: # time
                meta_text = (
                    f"생성일: {datetime.now().strftime('%Y-%m-%d %H:%M')}    "
                    f"대상 개체: {cfg['animal']}    "
                    f"구간 수: {cfg['n_win']}개 시간 구간"
                )
            fig.text(0.08, 0.925, meta_text, fontsize=8.5, color='#64748b')
            fig.add_artist(plt.Line2D([0.08, 0.92], [0.915, 0.915], color='#e2e8f0', lw=1, transform=fig.transFigure))

            y_pos = 0.89
            fig.text(0.08, y_pos, "1. 분석 개요", fontsize=11, fontweight='bold', color='#1e293b')
            y_pos -= 0.02
            if comp_type == "group":
                method_desc = (
                    f"본 리포트는 대조군(Dose {base_d})과 실험군(Dose {', '.join(str(d) for d in comp_ds)}) 간의 행동 지표를 비교한 결과입니다. "
                    "통계 검정 모델로는 선형 혼합 효과 모델(LME) 및 독립표본 t-검정이 사용되었습니다."
                )
            elif comp_type == "individual":
                method_desc = (
                    f"본 리포트는 개체 A({cfg['a_animal']})와 개체 B({cfg['b_animal']}) 간의 행동 지표 비교 통계 분석 결과입니다. "
                    "두 개체 간 행동 점수 평균의 차이는 독립표본 t-검정을 통해 검증되었습니다."
                )
            else: # time
                method_desc = (
                    f"본 리포트는 동일 개체({cfg['animal']})의 실험 시간 경과에 따른 행동 스코어 추이 분석 결과입니다. "
                    f"총 {cfg['n_win']}개 시간 구간별 편차 분석 및 첫/끝 구간 비교 검정이 시행되었습니다."
                )
            y_pos = draw_wrapped_text(fig, 0.08, y_pos, method_desc, 9, '#334155', width=90, line_height=0.016)
            y_pos -= 0.02

            fig.text(0.08, y_pos, "2. 통계 요약 (Results Table)", fontsize=11, fontweight='bold', color='#1e293b')
            ax_table = fig.add_axes([0.08, y_pos - 0.26, 0.84, 0.23])
            ax_table.axis('off')
            
            cell_text = []
            for _, row in disp.iterrows():
                line_cells = []
                for col in disp.columns:
                    val = str(row[col])
                    if col == "행동 지표":
                        val = val.split(' ')[0]
                    line_cells.append(val)
                cell_text.append(line_cells)
                
            columns = list(disp.columns)
            table = ax_table.table(cellText=cell_text, colLabels=columns, loc='center', cellLoc='center')
            table.auto_set_font_size(False)
            table.set_fontsize(7.5)
            table.scale(1.0, 1.6)
            for j in range(len(columns)):
                table[(0, j)].set_facecolor('#f1f5f9')
                table[(0, j)].get_text().set_weight('bold')
                table[(0, j)].get_text().set_color('#334155')
                
            y_pos -= 0.27

            fig.text(0.08, y_pos, "3. 행동 지표 비교 그래프", fontsize=11, fontweight='bold', color='#1e293b')
            ax_chart = fig.add_axes([0.08, y_pos - 0.22, 0.84, 0.19])
            
            x_indices = np.arange(len(disp))
            if comp_type == "group":
                w = 0.35
                ax_chart.bar(x_indices - w / 2, disp["대조군 평균"], w, label=f"대조군 (Dose {cfg['base_dose']})", color='#4C72B0')
                ax_chart.bar(x_indices + w / 2, disp["실험군 평균"], w, label="실험군", color='#C44E52')
            elif comp_type == "individual":
                # 호출부에서 '개체 A/B 평균' 컬럼이 '대조군/실험군 평균'으로 rename 되어 넘어온다.
                a_col = "대조군 평균" if "대조군 평균" in disp.columns else [c for c in disp.columns if "개체 A" in c][0]
                b_col = "실험군 평균" if "실험군 평균" in disp.columns else [c for c in disp.columns if "개체 B" in c][0]
                w = 0.35
                ax_chart.bar(x_indices - w / 2, disp[a_col], w, label=f"개체 A ({cfg.get('a_animal', 'A')})", color='#4C72B0')
                ax_chart.bar(x_indices + w / 2, disp[b_col], w, label=f"개체 B ({cfg.get('b_animal', 'B')})", color='#C44E52')
            else: # time
                win_cols = [c for c in disp.columns if "구간" in c]
                n_w = len(win_cols)
                w = 0.8 / n_w
                colors = ['#4C72B0', '#55A868', '#C44E52', '#8172B2', '#CCB974', '#64B5CD']
                for idx, win in enumerate(win_cols):
                    ax_chart.bar(x_indices - 0.4 + (idx + 0.5)*w, disp[win], w, label=win, color=colors[idx % len(colors)])

            ax_chart.set_xticks(x_indices)
            ax_chart.set_xticklabels([name.split(' ')[0] for name in disp["행동 지표"]], fontsize=8.5)
            ax_chart.set_ylabel('평균 점수', fontsize=8.5)
            ax_chart.legend(fontsize=8, frameon=False, loc='upper right')
            for sp in ['top', 'right']:
                ax_chart.spines[sp].set_visible(False)
            ax_chart.spines['bottom'].set_color('#cbd5e1')
            ax_chart.spines['left'].set_color('#cbd5e1')
            
            y_pos -= 0.28

            fig.text(0.08, y_pos, "4. AI 해석 및 통계 고찰", fontsize=11, fontweight='bold', color='#1e293b')
            y_pos -= 0.02
            
            ai_desc = ""
            if lines:
                ai_desc = "• " + "\n• ".join(lines)
            else:
                ai_desc = "• 관찰 대상 모든 지표에서 통계적으로 유의미한 행동 수치 변화는 감지되지 않았습니다 (p ≥ 0.05)."
                
            y_pos = draw_wrapped_text(fig, 0.08, y_pos, ai_desc, 8.5, '#334155', width=90, line_height=0.015)

        fig.text(0.08, 0.03, "Generated by Laboratory AI Platform", fontsize=7.5, color='#94a3b8')
        pdf.savefig(fig)
        plt.close(fig)
        
    buf.seek(0)
    return buf.getvalue()


def build_comparison_pptx(cfg, result, disp, lines, comp_type="group"):
    """비교 분석 결과를 PPTX로 생성 (프레젠테이션 스타일)"""
    from pptx import Presentation
    from pptx.util import Inches, Pt
    from pptx.dml.color import RGBColor
    import io
    import pandas as pd
    from datetime import datetime
    
    prs = Presentation()
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)
    
    c_dark = RGBColor(15, 23, 42)
    c_blue = RGBColor(37, 99, 235)
    c_gray = RGBColor(100, 116, 139)
    c_dark_text = RGBColor(30, 41, 59)

    # ── Slide 1: 표지 ──
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    fill = slide.background.fill
    fill.solid()
    fill.fore_color.rgb = c_dark
    
    txBox = slide.shapes.add_textbox(Inches(1.0), Inches(2.2), Inches(11.3), Inches(3.0))
    tf = txBox.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    p.text = cfg.get("title", "비교 분석 프레젠테이션")
    p.font.size = Pt(40)
    p.font.bold = True
    p.font.color.rgb = RGBColor(255, 255, 255)
    
    p2 = tf.add_paragraph()
    p2.text = f"발행일: {datetime.now().strftime('%Y-%m-%d %H:%M')}  |  통계 분석 보고서"
    p2.font.size = Pt(16)
    p2.font.color.rgb = c_gray
    p2.space_before = Pt(20)

    # ── Slide 2: 분석 개요 ──
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    txBox = slide.shapes.add_textbox(Inches(1.0), Inches(0.6), Inches(11.3), Inches(1.0))
    p = txBox.text_frame.paragraphs[0]
    p.text = "1. 분석 개요 및 실험 디자인"
    p.font.size = Pt(24)
    p.font.bold = True
    p.font.color.rgb = c_blue
    
    txBox2 = slide.shapes.add_textbox(Inches(1.0), Inches(1.8), Inches(11.3), Inches(4.5))
    tf2 = txBox2.text_frame
    tf2.word_wrap = True
    
    def add_bullet(tf, title, desc):
        p = tf.add_paragraph() if tf.paragraphs[0].text else tf.paragraphs[0]
        p.text = "• " + title
        p.font.size = Pt(18)
        p.font.bold = True
        p.font.color.rgb = c_dark_text
        p.space_after = Pt(6)
        
        p_desc = tf.add_paragraph()
        p_desc.text = "  " + desc
        p_desc.font.size = Pt(15)
        p_desc.font.color.rgb = c_gray
        p_desc.space_after = Pt(24)
        
    if comp_type == "group":
        add_bullet(tf2, "실험 목적", "약물(Yohimbine) 투여 조건별 5종 행동 스코어 변화 패턴을 통계적으로 비교 분석합니다.")
        add_bullet(tf2, "비교 그룹", f"대조군 Dose {cfg.get('base_dose', 0)} ({result['meta']['n_base']}마리) vs 실험군 Dose {', '.join(str(d) for d in cfg.get('comp_doses', [6]))} ({result['meta']['n_comp']}마리)")
        add_bullet(tf2, "적용 통계 모델", "선형 혼합 효과 모델(LME)을 통한 개체 간의 무작위 효과 통제 및 고정 효과(약물 효과) 검증.")
    elif comp_type == "individual":
        add_bullet(tf2, "실험 목적", "동일 조건 내 서로 다른 두 개체(개체 A vs 개체 B)의 행동 패턴 차이를 통계적으로 분석합니다.")
        add_bullet(tf2, "비교 대상", f"개체 A: {cfg.get('a_animal', '')} vs 개체 B: {cfg.get('b_animal', '')}")
        add_bullet(tf2, "적용 통계 모델", "독립표본 t-검정(Student's t-test)을 통한 지표별 평균 차이 유의성 검정.")
    else: # time
        add_bullet(tf2, "실험 목적", "동일 개체의 실험 시간대 경과에 따른 행동 스코어 패턴의 변화를 종단적으로 분석합니다.")
        add_bullet(tf2, "분석 대상", f"마우스 ID: {cfg.get('animal', '')} (총 {cfg.get('n_win', 3)}개 시간 구간 분할)")
        add_bullet(tf2, "적용 통계 모델", "시간 구간별 독립표본 t-검정 및 첫/끝 구간 평균 변화율 검증.")

    # ── Slide 3: 통계 분석 요약 (표) ──
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    txBox = slide.shapes.add_textbox(Inches(1.0), Inches(0.6), Inches(11.3), Inches(1.0))
    p = txBox.text_frame.paragraphs[0]
    p.text = "2. 행동 지표별 비교 분석 요약"
    p.font.size = Pt(24)
    p.font.bold = True
    p.font.color.rgb = c_blue
    
    rows, cols = len(disp) + 1, len(disp.columns)
    table_shape = slide.shapes.add_table(rows, cols, Inches(1.0), Inches(1.6), Inches(11.3), Inches(4.5))
    table = table_shape.table
    
    col_names = [col.replace("개체 A", "Animal A").replace("개체 B", "Animal B") for col in disp.columns]
    for j, name in enumerate(col_names):
        cell = table.cell(0, j)
        cell.text = name
        cell.fill.solid()
        cell.fill.fore_color.rgb = RGBColor(226, 232, 240)
        for p_t in cell.text_frame.paragraphs:
            p_t.font.bold = True
            p_t.font.size = Pt(13)
            p_t.font.color.rgb = c_dark_text
            p_t.alignment = 1
            
    for i, (_, row) in enumerate(disp.iterrows()):
        for j, col in enumerate(disp.columns):
            cell = table.cell(i+1, j)
            val = str(row[col])
            if col == "행동 지표":
                val = val.split(' ')[0]
            cell.text = val
            for p_t in cell.text_frame.paragraphs:
                p_t.font.size = Pt(12)
                p_t.font.color.rgb = c_dark_text
                p_t.alignment = 1
                if j == 0 or j == cols - 1:
                    p_t.font.bold = True
                if j == cols - 1:
                    if "유의함" in val or "유의" in val:
                        p_t.font.color.rgb = RGBColor(22, 101, 52)
                    else:
                        p_t.font.color.rgb = c_gray

    # ── Slide 4: 핵심 요약 ──
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    txBox = slide.shapes.add_textbox(Inches(1.0), Inches(0.6), Inches(11.3), Inches(1.0))
    p = txBox.text_frame.paragraphs[0]
    p.text = "3. 주요 결론 및 해석 (Conclusion)"
    p.font.size = Pt(24)
    p.font.bold = True
    p.font.color.rgb = c_blue
    
    txBox2 = slide.shapes.add_textbox(Inches(1.0), Inches(1.8), Inches(11.3), Inches(4.5))
    tf2 = txBox2.text_frame
    tf2.word_wrap = True
    
    if lines:
        for line in lines:
            p = tf2.add_paragraph() if tf2.paragraphs[0].text else tf2.paragraphs[0]
            p.text = "• " + line.replace("**", "")
            p.font.size = Pt(16)
            p.font.color.rgb = c_dark_text
            p.space_after = Pt(14)
    else:
        p = tf2.paragraphs[0]
        p.text = "• 통계적 유의수준(p < 0.05) 검정 상으로 선택한 조건 간의 행동 지표 평균값 차이는 일반적인 개체 차 범위 이내에 위치하여 유의한 격차는 검출되지 않았습니다."
        p.font.size = Pt(18)
        p.font.color.rgb = c_dark_text
        p.space_after = Pt(14)
        
    buf = io.BytesIO()
    prs.save(buf)
    buf.seek(0)
    return buf.getvalue()
